# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-31 09:12
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='crops',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop', models.CharField(choices=[('cotton', 'cotton'), ('groundnut', 'groundnut'), ('maize', 'maize'), ('paddy', 'paddy'), ('plain', 'plain'), ('sugarcane', 'sugarcane'), ('turmeric', 'turmeric')], default='paddy', max_length=20)),
                ('crop_area', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='farm_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poly', django.contrib.gis.db.models.fields.PolygonField(default='', srid=4326)),
                ('area', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='house_hold',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mon_income', models.IntegerField(default=0)),
                ('point', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('links', models.CharField(default='gfdxgh', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='persons_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('gender', models.CharField(max_length=2)),
                ('DOB', models.DateField(null=True)),
                ('house_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farms.house_hold')),
            ],
        ),
        migrations.CreateModel(
            name='season_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(choices=[('monsoon', 'monsoon'), ('rainy', 'rainy'), ('summer', 'summer'), ('winter', 'winter')], default='summer', max_length=20)),
                ('crop', models.CharField(choices=[('cotton', 'cotton'), ('groundnut', 'groundnut'), ('maize', 'maize'), ('paddy', 'paddy'), ('plain', 'plain'), ('sugarcane', 'sugarcane'), ('turmeric', 'turmeric')], default='paddy', max_length=20)),
                ('area', models.DecimalField(decimal_places=2, max_digits=6)),
                ('farm_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farms.farm_info')),
            ],
        ),
        migrations.CreateModel(
            name='well_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.DecimalField(decimal_places=6, max_digits=15)),
                ('lon', models.DecimalField(decimal_places=6, max_digits=15)),
                ('depth_in_meters', models.DecimalField(decimal_places=2, max_digits=6)),
                ('Avg_wateryield', models.DecimalField(decimal_places=2, max_digits=8)),
                ('farm_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farms.farm_info')),
            ],
        ),
        migrations.CreateModel(
            name='well_observation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depth_in_meters', models.DecimalField(decimal_places=2, max_digits=6)),
                ('date_of_observation', models.DateTimeField(null=True)),
                ('wateryield', models.DecimalField(decimal_places=2, max_digits=8)),
                ('well_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farms.well_info')),
            ],
        ),
        migrations.AddField(
            model_name='farm_info',
            name='house_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farms.house_hold'),
        ),
        migrations.AddField(
            model_name='crops',
            name='farm_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farms.farm_info'),
        ),
    ]
