# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-31 09:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0002_auto_20171031_0914'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='well_info',
            name='point',
        ),
        migrations.AddField(
            model_name='well_info',
            name='lat',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=15),
        ),
        migrations.AddField(
            model_name='well_info',
            name='lon',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=15),
        ),
    ]
