# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-03 15:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0003_auto_20171031_0933'),
    ]

    operations = [
        migrations.CreateModel(
            name='farm_yield',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Yield', models.IntegerField(default=0)),
                ('farm_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farms.farm_info')),
            ],
        ),
        migrations.AlterField(
            model_name='crops',
            name='crop',
            field=models.CharField(choices=[('paddy', 'paddy'), ('groundnut', 'groundnut'), ('maize', 'maize'), ('sugarcane', 'sugarcane'), ('turmeric', 'turmeric')], default='paddy', max_length=20),
        ),
        migrations.AlterField(
            model_name='season_info',
            name='crop',
            field=models.CharField(choices=[('paddy', 'paddy'), ('groundnut', 'groundnut'), ('maize', 'maize'), ('sugarcane', 'sugarcane'), ('turmeric', 'turmeric')], default='paddy', max_length=20),
        ),
    ]
